# Site settings
title: "Kirk Lange"
email: example@example.com
description: "Personal Blog and Portfolio"
baseurl: ""
url: "http://kirklange.com"
title_description: "Programmer? Pianist? Same difference. They both work at 
the keyboard.<br><hr>Are you an employer I am trying to impress?<br>\
Click here <div style=\"display: inline\" onclick=\"menuClick()\">\
<i class=\"fa fa-file-alt\"></i></div> to read my About Me page."
title_image: "https://avatars.githubusercontent.com/u/10791893"
google_analytics:
github_repository: https://github.com/kirklange/kirklange.github.io
addthis_id:
post_limit: 3

# Social usernames/URLs
disqus_account:
stackoverflow_link:
reddit_username: kirk_lange
google_plus_link:
facebook_link:
twitter_username:
instagram_username:
linkedin_link: http://www.linkedin.com/in/kirk-lange/
xing_link:

# Footer
footer_left: "<i class=\"fa fa-code-branch\"></i> of <a target=\"_blank\" href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noire</a>"
footer_right: "<i class=\"fa fa-code\"></i> on <a target=\"_blank\" href=\"https://github.com/kirklange/kirklange.github.io\">GitHub</a>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

# Plugins
plugins_dir:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
    #  - jekyll-avatar
  - jemoji
  - jekyll-mentions

jekyll-mentions: https://reddit.com/user/
